# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a619d60c1cb62f160ca4afa651f0715d74ef7e44a20ce8f864ceee18261d7c07b11fde6faf7e34ac1c244e41d7cd9fda24557a07ac1f952cceccfaa1d0fdf2

test:
  secret_key_base: edd7eabf4939f549d295958aad5c9f6edbbbab73e538e500cc8405e6cbe04c1dc79a73a0d6484f71afec536b9bbc1292bd4f24de4164c20051a5c38dcac03305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
